language: dlang
install:
 - sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
 - sudo apt-get update
 - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
 - sudo apt-get update
 - sudo apt-get -y install dmd-bin
 - gem install cucumber rspec aruba
script: dub test
script: cucumber -n Core
script: cucumber --tags @wip features/wire_protocol.feature
