language: dlang
install:
 - sudo wget http://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
 - sudo apt-get update
 - sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring
 - sudo apt-get update
 - sudo apt-get -y install dmd-bin libcurl4-gnutls-dev
 - gem install cucumber rspec aruba
 - git clone https://github.com/rejectedsoftware/dub
 - cd dub
 - ./build.sh
 - cd ..
script: dub/dub test
script: cucumber --tags ~@wip features/wire_protocol.feature
