//Automatically generated by dtest, do not edit by hand
import unit_threaded.runner;
import std.stdio;

int main(string[] args) {
    writeln("\nAutomatically generated file tests/ut.d");
    writeln(`Running unit tests from dirs ["tests"]
`);
    return runTests!("tests.server_match", "tests.calculator.feature", "tests.calculator.steps", "tests.calculator.impl", "tests.keywords", "tests.reflection", "tests.match", "tests.server", "tests.given_when_then")(args);
}
